default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, main, --pattern, 0_.*_X]
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-executables-have-shebangs
    -   id: forbid-new-submodules
    -   id: check-yaml
        exclude: '.clang-format'
    -   id: check-xml
    -   id: end-of-file-fixer
        types_or: [c, shell, python]
    -   id: trailing-whitespace
        types_or: [c, shell, python, xml]
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: [--fix=lf]
-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
-   repo: local
    hooks:
    - id: check-null-false-returns
      name: check for null / false return mistmatch
      language: script
      entry: ./contrib/ci/check-null-false-returns.py
    - id: clang-format
      name: clang-format
      language: script
      entry: ./contrib/reformat-code.py
      types: [c]
    - id: check-license
      name: Check license header
      types_or: [shell, c, python]
      language: script
      entry: ./contrib/ci/check-license.py
