.\" Report problems in https://github.com/hughsie/libxmlb
.TH man 1 "18 April 2022" @PACKAGE_VERSION@ "xb-tool man page"
.SH NAME
xb-tool \- standalone XMLb utility
.SH SYNOPSIS
xb-tool [CMD]
.SH DESCRIPTION
This tool allows creating, dumping and querying binary XML blobs.
.PP
Additionally \fBxb-tool\fR can be used to profile specfic tokenized queries.
.SH OPTIONS
The xb-tool command takes various options depending on the action.
Run \fBxb-tool --help\fR for the full list.
.SH EXIT STATUS
Commands that successfully execute will return "0", otherwise "1".
.SH BUGS
No known bugs.
.SH AUTHOR
Richard Hughes (richard@hughsie.com)
