FROM debian:unstable

RUN apt-get update -qq
RUN apt-get install -yq --no-install-recommends \
	gcovr \
	gobject-introspection \
	gtk-doc-tools \
	libgirepository1.0-dev \
	libglib2.0-dev \
	shared-mime-info \
	uuid-dev \
	meson \
	pkg-config
RUN mkdir /build
WORKDIR /build
