FROM fedora:28

RUN dnf -y update
RUN dnf -y install \
	gcovr \
	git \
	glib2-devel \
	gobject-introspection-devel \
	gtk-doc \
	libabigail \
	libstemmer-devel \
	libuuid-devel \
	meson \
	shared-mime-info \
	redhat-rpm-config

RUN mkdir /build
WORKDIR /build
